
#include "libjpg/jaricom.c"
#include "libjpg/jcapimin.c"
#include "libjpg/jcapistd.c"
#include "libjpg/jcarith.c"
#include "libjpg/jctrans.c"
#include "libjpg/jcparam.c"
#include "libjpg/jdatadst.c"
#include "libjpg/jcinit.c"
#include "libjpg/jcmaster.c"
#include "libjpg/jcmainct.c"
#include "libjpg/jcprepct.c"
#include "libjpg/jccolor.c"
#include "libjpg/jcsample.c"

#undef FIX
#include "libjpg/jcdctmgr.c"
#undef FIX
#undef CONST_BITS
#undef DESCALE
#include "libjpg/jfdctfst.c"
#undef FIX
#undef DESCALE
#include "libjpg/jfdctflt.c"
#undef FIX
#undef CONST_BITS
#undef FIX_0_541196100
#undef MULTIPLY
#include "libjpg/jfdctint.c"

#include "libjpg/jdapimin.c"
#include "libjpg/jdapistd.c"
#include "libjpg/jdtrans.c"
#include "libjpg/jdatasrc.c"
#include "libjpg/jdmarker.c"
#include "libjpg/jdhuff.c"
#include "libjpg/jdpostct.c"
#undef FIX
#undef CONST_BITS
#undef FIX_1_847759065
#undef MULTIPLY
#include "libjpg/jidctfst.c"
#undef DESCALE
#undef DEQUANTIZE
#include "libjpg/jidctflt.c"
#undef CONST_BITS
#undef FIX_1_847759065
#undef MULTIPLY
#undef DEQUANTIZE
#include "libjpg/jidctint.c"
#include "libjpg/jdsample.c"
#include "libjpg/jquant1.c"
#include "libjpg/jcomapi.c"
#include "libjpg/jutils.c"
#include "libjpg/jerror.c"
#include "libjpg/jmemmgr.c"
